os: linux
  
language: go

go:
  - 1.13.x

services:
  - docker

script:   
  - go test -v ./...
  - go build -o demo
  - docker build -t agrimmer/demo:latest ./
  - echo "$REGISTRY_PASSWORD" | docker login --username $REGISTRY_USER --password-stdin
  - docker push agrimmer/demo:latest
